# Generated by Django 4.2.1 on 2023-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bfm_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('place', models.CharField(max_length=300, verbose_name='장소')),
                ('kind', models.CharField(choices=[('TBF', '팀버핏'), ('BFP', '버핏플레이'), ('PIL', '필라테스')], max_length=10, verbose_name='종류')),
                ('credit', models.IntegerField(choices=[(50000, '5만원'), (70000, '7만원'), (100000, '10만원'), (150000, '15만원')], null=True, verbose_name='수업 가격(credit)')),
                ('max_count', models.IntegerField(verbose_name='수업 정원')),
                ('date', models.DateField(verbose_name='수업일')),
                ('stime', models.TimeField(verbose_name='수업 시작시간')),
                ('etime', models.TimeField(verbose_name='수업 종료시간')),
                ('remark', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': '수업',
                'verbose_name_plural': '수업',
                'db_table': 'class',
            },
        ),
        migrations.DeleteModel(
            name='mClass',
        ),
    ]
