# Generated by Django 4.2.1 on 2023-05-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bfm_class_delete_mclass'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bfm_class',
            table='bfm_class',
        ),
    ]
