# Generated by Django 4.2.1 on 2023-05-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_bfm_class_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bfm_Class',
            new_name='bf_Class',
        ),
        migrations.AlterModelTable(
            name='bf_class',
            table='bf_Class',
        ),
    ]
