# Generated by Django 4.2.1 on 2023-05-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_bf_class_options_bf_class_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bf_class',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='활성'),
        ),
    ]
