# Generated by Django 4.2.1 on 2023-05-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_bf_class_credit_alter_bf_class_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bf_class',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='수업 시작일'),
        ),
    ]
