# Generated by Django 4.2.1 on 2023-05-22 16:04

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_bf_class_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='bf_UserCredit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_date', models.DateField(verbose_name='크레딧 구매일')),
                ('user_id', models.IntegerField(default=1, verbose_name='user_id')),
                ('place', models.CharField(blank=True, max_length=300, null=True, verbose_name='장소(optional)')),
                ('credit', models.IntegerField(verbose_name='credit(원)')),
                ('enable', models.BooleanField(default=True, verbose_name='활성')),
                ('expire_period', computed_property.fields.ComputedIntegerField(compute_from='calc_expire_period', editable=False)),
                ('expire_date', computed_property.fields.ComputedDateField(compute_from='calc_expire_date', editable=False, null=True)),
                ('remark', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'UserCredit',
                'verbose_name_plural': 'UserCredit',
                'db_table': 'bf_UserCredit',
            },
        ),
    ]
