# Generated by Django 4.2.1 on 2023-05-22 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_remove_bf_usercredit_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='연락처')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='bf_Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_date', models.DateField(verbose_name='예약일')),
                ('enable', models.BooleanField(default=True, verbose_name='활성')),
                ('spent_credit', models.IntegerField(verbose_name='차감된 크레딧')),
                ('cancel_date', models.DateField(blank=True, null=True, verbose_name='예약취소일')),
                ('refund_credit', models.IntegerField(blank=True, null=True, verbose_name='환불된 크레딧')),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.bf_class')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Book',
                'db_table': 'bf_Book',
            },
        ),
    ]
