# Generated by Django 4.2.1 on 2023-05-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_profile_bf_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bf_book',
            name='book_date',
            field=models.DateTimeField(verbose_name='예약일'),
        ),
        migrations.AlterField(
            model_name='bf_book',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='예약취소일'),
        ),
    ]
