# Generated by Django 4.2.1 on 2023-05-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_bf_book_class_id_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bf_book',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='myapp.profile'),
        ),
    ]
