# Generated by Django 4.2.1 on 2023-05-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_bf_book_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bf_book',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
    ]
